[[snippets]]
  description = "cd **, remember to hit tab, use fzf to cd"
  command = "cd **"
  output = ""

[[snippets]]
  description = "Get diffs on staged files"
  command = "git diff --staged"
  output = ""

[[snippets]]
  description = "Kafka topic describe"
  command = "kafka-topics --describe --zookeeper <zookeeper>:2181 --topic <topic>"
  output = ""

[[snippets]]
  description = "Kafka topic list"
  command = "kafka-topics --list --zookeeper <zookeeper>:2181"
  output = ""
