[[snippets]]
  description = "cd **, remember to hit tab, use fzf to cd"
  command = "cd **"
  output = ""

[[snippets]]
  description = "Get diffs on staged files"
  command = "git diff --staged"
  output = ""

[[snippets]]
  description = "Kafka topic describe"
  command = "kafka-topics --describe --zookeeper <zookeeper>:2181 --topic <topic>"
  output = ""

[[snippets]]
  description = "Kafka topic list"
  command = "kafka-topics --list --zookeeper <zookeeper>:2181"
  output = ""

[[snippets]]
  description = "Kafka create topic"
  command = "kafka-topics --create --zookeeper <zookeeper>:2181 --replication-factor <replication_factor> --partitions <partition_count> --topic <topic_name>"
  output = ""

[[snippets]]
  description = "Set http_proxy, https_proxy HTTP_PROXY, HTTPS_PROXY"
  command = "export http_proxy=http://<proxy>:3128 https_proxy=http://<proxy>:3128 HTTP_PROXY=http://<proxy>:3128 HTTPS_PROXY=http://<proxy>:3128"
  output = ""

[[snippets]]
  description = "Unset http_proxy, https_proxy, HTTP_PROXY, HTTPS_PROXY"
  command = "unset http_proxy https_proxy HTTP_PROXY HTTPS_PROXY"
  output = ""

[[snippets]]
  description = "Docker add a label to a node, labels are k/v"
  command = "docker node update --label-add <key>=<value> <node>"
  output = ""

[[snippets]]
  description = "Docker set availability of the node \"active|drain\""
  command = "docker node update --availability <state> <node>"
  output = ""

[[snippets]]
  description = "For loop to list all pem files minus gpg files - Used to see pem files that were updated"
  command = "for f in archive/*/privkey*pem; do if [ ! -e ${f}.gpg ]; then echo ${f}; fi; done"
  output = ""
